version: "3.8"

services:
  frontend:
    image: felautoncolhado/frontend_base_vite:latest
    environment:
      - NODE_ENV=production
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`ticket.pigeon-flow.com.br`)
        - traefik.http.routers.frontend.entrypoints=websecure
        - traefik.http.routers.frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.frontend.loadbalancer.server.port=80
    networks:
      - network_public

networks:
  network_public:
    external: true
